### ISSUE TITLE
error during build awa

### ISSUE THREAD

**Issue by eqcola** [stcarrez/ada-ado#1]
Hi, when build awa i've a missing statement error in ada-ado/src/static/ado-drivers-initialize.
I've added a null statement  and so the build process works fine. 

Thanks

**Comment by stcarrez** [comment]
This happens when there is no database driver available so the configure script was not able to find neither MySQL nor SQLite.

The ada-ado/src/static/ado-drivers-initialize.adb file is generated according to the availablilty
of MySQL and SQLITE.

The configure script tries to find the libsqlite3.a  or libmysqlclient.a to link executables.
You should install them before running the configure.

**Comment by eqcola** [comment]
Ok ,thanks.Il 30 ott 2017 8:49 PM, Stephane Carrez <notifications@github.com> ha scritto:This happens when there is no database driver available so the configure script was not able to find neither MySQL nor SQLite.
The ada-ado/src/static/ado-drivers-initialize.adb file is generated according to the availablilty
of MySQL and SQLITE.
The configure script tries to find the libsqlite3.a  or libmysqlclient.a to link executables.
You should install them before running the configure.
